// src/tsx/App.tsx
import React, { useState, useEffect } from 'react';
import ExampleComponent from './components/ExampleComponent'

const App: React.FC = () => {
  const [text, setText] = useState('ExampleComponent');
  useEffect(() => {
    console.log('React is ready.');
  }, []);
  return (
    <>
      <ExampleComponent message={text} />
    </>
  )
}

export default App;

// src/vue/App.vue
<template>
  <router-view />
  <example-component :message="data.text" />
</template>

<script lang="ts" setup>
  import { reactive } from 'vue';
  import { useStore } from '../ts/store';
  import ExampleComponent from './components/ExampleComponent.vue';
  const store = useStore();
  const data = reactive({
    text: 'ExampleComponent'
  });
  store.updateMessage('state updated');
  console.log(`Vue.js is ready. ${store.message}`);
</script>
